---
dependency:
  name: galaxy
  role-file: molecule/default/requirements.yml
driver:
  name: docker
platforms:
  - name: master-1
    image: ${MOLECULE_DISTRO:-geerlingguy/docker-debian10-ansible}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    network: docker_swarm
    command: ${MOLECULE_COMMAND:-"/lib/systemd/systemd"}
    privileged: true
    pre_build_image: true
    groups:
      - docker_swarm_manager
  - name: master-2
    image: ${MOLECULE_DISTRO:-geerlingguy/docker-debian10-ansible}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    network: docker_swarm
    command: ${MOLECULE_COMMAND:-"/lib/systemd/systemd"}
    privileged: true
    pre_build_image: true
    groups:
      - docker_swarm_manager
  - name: worker-1
    image: ${MOLECULE_DISTRO:-geerlingguy/docker-debian10-ansible}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    network: docker_swarm
    command: ${MOLECULE_COMMAND:-"/lib/systemd/systemd"}
    privileged: true
    pre_build_image: true
    groups:
      - docker_swarm_worker
provisioner:
  name: ansible
verifier:
  name: ansible
