---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: get swarm facts
    docker_swarm_info:
      nodes: yes
    register: _swarm
    when: "'docker_swarm_manager' in group_names"

  - name: get docker info
    docker_host_info:
    register: _dockerinfo

  - name: managers must be managers
    assert:
      that:
        - _dockerinfo.host_info.Swarm.LocalNodeState == "active"
        - "_dockerinfo.host_info.Swarm.Managers == {{ groups['docker_swarm_manager'] | length }}"
    when: "'docker_swarm_manager' in group_names"

  - name: workers must be workers
    assert:
      that:
        - _dockerinfo.host_info.Swarm.LocalNodeState == "active"
        - _dockerinfo.host_info.Swarm.Managers is not defined
    when:
      - "'docker_swarm_worker' in group_names"